[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/platform-win",
    "crates/cli",
    "crates/gui",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
rustcapture-core = { path = "crates/core" }
platform-win = { path = "crates/platform-win" }
thiserror = "2"
png = "0.18"
jpeg-encoder = "0.7"
time = { version = "0.3", features = ["local-offset"] }
pico-args = "0.5"
