[package]
name = "rustcapture-core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
png = { workspace = true }
jpeg-encoder = { workspace = true }
time = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
fontdue = { workspace = true }
crc32fast = { workspace = true }
flate2 = { workspace = true }
